[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/admin"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
