[build]
builder = "nixpacks"
buildCommand = "NPM_CONFIG_PRODUCTION=false npm install --no-audit --no-fund && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/_health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
